# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/gms/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)
include $(call first-makefiles-under,$(LOCAL_PATH))
ifneq ($(filter arm64,$(TARGET_ARCH)),)

endif
